# [font]
# size = 12.0
#
# [font.normal]
# family = "JetBrainsMono Nerd Font"
# #style = "Regular"
#
# [window]
# opacity = 0.7
#
# #[window.padding]
# #x = 12
# #y = 12

general.import = ["~/.cache/wal/colors-alacritty.toml"]

# Colors - Use pywal-generated colors
# Font Settings
[font]
size = 12.0

[font.normal]
family = "FiraCode Nerd Font Mono"

[font.bold]
family = "FiraCode Nerd Font Mono"

[font.italic]
family = "FiraCode Nerd Font Mono"

[font.bold_italic]
family = "FiraCode Nerd Font Mono"

# Keybinds
[keyboard]
bindings = [{ key = "V", mods = "Control", action = "Paste" }]

# Clipboard settings - use external program for clipboard support
[selection]
save_to_clipboard = true
